services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: lcslsdcontainer.azurecr.io/nginx:latest  # Your image in ACR
    user: root
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lcpserver
      - lsdserver
    networks:
      - app-network

  lcpserver:
    build:
      context: ..  # This assumes your Dockerfile is in the ci folder and you're building from the repository root
      dockerfile: ci/Dockerfile
      target: runtime-lcp
    image: lcslsdcontainer.azurecr.io/lcpserver:latest
    entrypoint: ["/bin/sh", "ci/entrypoint.sh"]
    user: root
    ports:
      - "8989:8989"
    networks:
      - app-network

  lsdserver:
    build:
      context: ..  # Same as for lcpserver
      dockerfile: ci/Dockerfile
      target: runtime-lsd
    image: lcslsdcontainer.azurecr.io/lsdserver:latest
    entrypoint: ["/bin/sh", "ci/entrypoint.sh"]
    user: root
    ports:
      - "8990:8990"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
