services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: lcslsdcontainer.azurecr.io/nginx:latest  # Local image name
    user: root
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME:-./nginx}/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lcpserver
      - lsdserver
    networks:
      - app-network

  lcpserver:
    build:
      context: ..  # Path to your Dockerfile
      dockerfile: ci/Dockerfile
      target: runtime-lcp
    image: lcslsdcontainer.azurecr.io/lcpserver:latest
    volumes:
      - ./ci/config.yaml:/app/config.yaml:ro
      - ./ci/data/files/storage:/data/files/storage
      - ./ci/data/files/encrypted:/data/files/encrypted
    environment:
      LCP_PUBLIC_BASE_URL: "http://test.tes"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    user: root  # Add this line
    ports:
      - "8989:8989"
    networks:
      - app-network

  lsdserver:
    build:
      context: ..  # Path to your Dockerfile
      dockerfile: ci/Dockerfile
      target: runtime-lsd
    image: lcslsdcontainer.azurecr.io/lsdserver:latest
    volumes:
      - ./ci/config.yaml:/app/config.yaml:ro
      - ./ci/data/files/storage:/data/files/storage
      - ./ci/data/files/encrypted:/data/files/encrypted
    environment:
      LSD_PUBLIC_BASE_URL: "http://test.tes"
    user: root  # Add this line
    ports:
      - "8990:8990"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
